### ISSUE TITLE
Sen211

### ISSUE THREAD

**Issue by heavenlyboy1** [SpiDher/Team_1#3]
**Validation and verification process **
First step the link was provided and it was opened ... 
The link loads well @milliseconds and the layout is perfect although the work is still in progress ...

First observation : The first panel opened ... But the rest of the 6 didn't ...

Secondly: The code source was sorted ... 
1: the validation process took place in w3schools website...

After the source code sorted ...

2: the element <p> isn't a child element of ul in line 17 column 17 and line 17 column 19

Also line 18 column 17 and line 18 column 19

Also line 19 column 17 and 19 column 19

Also line 20 column 17 and 20 column 19

Another observation The nav section has a stray comment 
-->
it should be removed 

Semantic improvement: Also the header should be considered to be wrapped inside the div for more concise view 

A typo error was spotted ...

**Intoduction **  instead of _Introduction_

Css and external file dependencies ...
Ensure Demo.css exist in the same directory as the HTML file 

Empty image alt attribute 

Check for the alt="" and specify 

I should recommend using <button> attribute in the navigation for better accessibility 

Meta name ="viewport" is okay and the charset="UTF-8" makes it standardize 

As the work progresses ... We the validation and verification team will look deeper into it time to time to ensure proper, accurate and eesponsive code run

**Comment by SpiDher** [comment]
Fixed
