### ISSUE TITLE
Sen211 validation 

### ISSUE THREAD

**Issue by T3gaed** [SpiDher/Team_1#4]
After getting the link I headed off to webpage test.org, and validation was conducted and the following are the result:

The site is quick to connect and to deliver initial codes and render content quickly

The site has a good layout stability and took little time to become interactive. It has two accessibility issues 
1. HTML content was mostly generated server side 

Several fonts are loaded with settings that hide text while they are loading.
When fonts are loaded with default display settings, like font-display="block", browsers will hide text entirely for several seconds instead of showing text with a fallback font.

Suggested remedy
This experiment adds font-display="swap" to custom fonts to show text sooner.

Is it Resilient?
Looks great! This site had no render-blocking 3rd party requests that could be a single point of failure. It had no security issues. HTML content was mostly generated server-side.

Zero security vulnerabilities were detected by Snyk
Snyk has found 0 security vulnerabilities with included packages.

That's all for  now

**Comment by SpiDher** [comment]
Fixed

**Comment by SpiDher** [comment]
Fuxed

**Comment by T3gaed** [comment]
There is another Error spotted in the project ... 


Error: An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.
From line 26, column 13; to line 26, column 69
          <img src="./modules/res/logo-main.png" class="g4-logo" />↩     
Info: Trailing slash on void elements has no effect and interacts badly with unquoted attribute values.
From line 26, column 13; to line 26, column 69
          <img src="./modules/res/logo-main.png" class="g4-logo" />↩


All for now
